# Generated by Django 5.0.7 on 2024-08-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yer',
            old_name='isim',
            new_name='goruntu_adi',
        ),
        migrations.AddField(
            model_name='yer',
            name='genel_yap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yer',
            name='kisa_ad',
            field=models.CharField(default='DEFAULT_VALUE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yer',
            name='tanim',
            field=models.TextField(blank=True, null=True),
        ),
    ]
