# Generated by Django 5.0.7 on 2024-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_isim_yer_goruntu_adi_yer_genel_yap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.CharField(default='Default Company', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default='Medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='program_module',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.CharField(default='Medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='special_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(default='Bug', max_length=50),
            preserve_default=False,
        ),
    ]
