# Generated by Django 5.0.7 on 2024-08-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_attachment_ticket_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(default='default_user', max_length=100),
            preserve_default=False,
        ),
    ]
