# Generated by Django 5.0.7 on 2024-08-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_assigned_to_alter_ticket_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.CharField(default='Default Company', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default='Medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='program_module',
            field=models.CharField(default='General Module', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(default='Medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(default='Bug', max_length=50),
            preserve_default=False,
        ),
    ]
