# Generated by Django 5.0.7 on 2024-08-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_status_alter_ticket_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email_notification',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='special_group',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.CharField(choices=[('CompanyA', 'Company A'), ('CompanyB', 'Company B'), ('CompanyC', 'Company C')], default='CompanyA', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='program_module',
            field=models.CharField(choices=[('ModuleA', 'Module A'), ('ModuleB', 'Module B'), ('ModuleC', 'Module C')], default='ModuleA', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], default='Minor', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature Request'), ('Support', 'Support Request')], default='Bug', max_length=50),
        ),
    ]
