# Generated by Django 5.0.7 on 2024-08-13 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='program_module',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.yer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='summary',
            field=models.CharField(max_length=255),
        ),
    ]
