# Generated by Django 5.0.7 on 2024-08-14 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_company_alter_ticket_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.yer'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
