# Generated by Django 5.0.7 on 2024-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketupdate',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
