# Generated by Django 5.0.7 on 2024-08-23 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_ticketupdate_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='content',
        ),
        migrations.AddField(
            model_name='response',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(default='Open', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
