# Generated by Django 5.0.7 on 2024-08-26 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from datetime import timedelta  # timedelta import edildi


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_remove_response_content_response_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='response',
            name='time_spent',
            field=models.DurationField(default=timedelta()),  # Hata burada düzeltildi
            preserve_default=False,
        ),
    ]
