# Generated by Django 5.0.7 on 2024-08-26 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_response_assigned_to_alter_response_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
