# Generated by Django 5.0.7 on 2024-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_response_assigned_to_alter_response_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketupdate',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
