# Generated by Django 5.0.7 on 2024-08-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_alter_ticketupdate_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
