# Generated by Django 5.0.7 on 2024-08-28 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_alter_response_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
