# Generated by Django 5.0.7 on 2024-08-29 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_response_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='email_notification',
        ),
        migrations.AlterField(
            model_name='response',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='response',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
