# Generated by Django 5.0.7 on 2024-08-29 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_remove_response_email_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
