# Generated by Django 5.0.7 on 2024-08-31 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_response_email_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='response',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='response',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
