# Generated by Django 5.0.7 on 2024-08-31 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_response_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketupdate',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='ticketupdate',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketupdate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='TicketUpdate',
        ),
    ]
