# Generated by Django 5.0.7 on 2024-08-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_ticketupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketupdate',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=20),
        ),
    ]
