# Generated by Django 5.0.7 on 2024-09-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_alter_ticketupdate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('login_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
