# Generated by Django 5.0.7 on 2024-09-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_kullanici'),
    ]

    operations = [
        migrations.AddField(
            model_name='yer',
            name='kullanicilar',
            field=models.ManyToManyField(related_name='yerler', to='tickets.kullanici'),
        ),
    ]
