# Generated by Django 5.0.7 on 2024-09-04 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_yer_kullanicilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yer',
            name='kullanicilar',
            field=models.ManyToManyField(related_name='yerler', to=settings.AUTH_USER_MODEL),
        ),
    ]
