# Generated by Django 5.0.7 on 2024-09-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_alter_yer_kullanicilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='role',
            field=models.CharField(choices=[('ENDUSER', 'End User'), ('ITMANAGER', 'IT Manager'), ('OTHERMANAGER', 'Other Manager'), ('ITSTAFF', 'IT Staff')], default='ENDUSER', max_length=50),
        ),
    ]
