# Generated by Django 5.0.7 on 2024-09-09 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='yerler',
            field=models.ManyToManyField(blank=True, related_name='custom_user_yerler', to='tickets.yer'),
        ),
        migrations.AlterField(
            model_name='yer',
            name='kullanicilar',
            field=models.ManyToManyField(related_name='yer_kullanicilari', to=settings.AUTH_USER_MODEL),
        ),
    ]
